name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: self-hosted
    
    strategy:
      matrix:
        java-version: [8]

    steps:
    - uses: actions/checkout@v3
    - name: Use Java Version ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - run: chmod +x build.sh
    - run: chmod +x run_sit.sh
    - run: ./build.sh
    - run: ./run_sit.sh
      working-directory: /home/esopadmin/UAT/gitaction/java_service/actions-runner/_work/esop_server_rule/esop_server_rule
      
      
